[project]
name = "self-heal-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.8",
    "langchain-community>=0.4.1",
    "langchain-core>=0.3.0",
    "langchain-groq>=1.1.2",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.1.8",
    "python-dotenv>=1.2.2",
    "mlflow>=2.10.0",
    "pandas>=2.0.0",
]
